name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3
      -  run: ls -la
      -  run: docker build -t antoine_noel:22


#docker build
#docker images
#docker push
