name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3
      -  run: ls -la
      -  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -  run: docker build -t ${{ secrets.DOCKER_USERNAME }}/antoine_noel:22 .
      -  run: docker images
      -  run: docker tag ${{ secrets.DOCKER_USERNAME }}/antoine_noel:22 ${{ secrets.DOCKER_USERNAME }}/antoine_noel:22
      -  run: docker push ${{ secrets.DOCKER_USERNAME }}/antoine_noel:22


#docker push
