name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v3
      -  run: ls -la


#checkout code
#ls
#docker build
#docker images
#docker push
